# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/eastc/Desktop/CPE487/Cmod-A7-15T/Lab4/hexcalc.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
